services:
  digipres.lib.unb.ca:
    build:
      args:
        DSPACE_REST_PORT: '8080'
        DSPACE_REST_SSL: 'false'
      context: .
    restart: unless-stopped
    container_name: digipres.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "4000"
    networks:
      - digipres.lib.unb.ca
    ports:
      - "9988:4000"
  digipres.dspace.lib.unb.ca:
    build:
      context: dspace/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - digipres.lib.unb.ca
  digipres.postgres.lib.unb.ca:
    build:
      context: postgres/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "5432"
    networks:
      - digipres.lib.unb.ca
  digipres-solr-lib-unb-ca:
    build:
      context: solr/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    networks:
      - digipres.lib.unb.ca
networks:
  digipres.lib.unb.ca:
    name: digipres.lib.unb.ca
