services:
  digpres.lib.unb.ca:
    build:
      args:
        DSPACE_REST_PORT: '8080'
        DSPACE_REST_SSL: 'false'
      context: .
    restart: unless-stopped
    container_name: digpres.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "4000"
    networks:
      - digpres.lib.unb.ca
    ports:
      - "9988:4000"
  digpres.dspace.lib.unb.ca:
    build:
      context: dspace/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - digpres.lib.unb.ca
  digpres.postgres.lib.unb.ca:
    build:
      context: postgres/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "5432"
    networks:
      - digpres.lib.unb.ca
  digpres-solr-lib-unb-ca:
    build:
      context: solr/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    networks:
      - digpres.lib.unb.ca
networks:
  digpres.lib.unb.ca:
    name: digpres.lib.unb.ca
